add wifi setup, fix logos with transparent spaces
the-papi/MoonClock pull request #8
Opened 2021-12-23 10:29 UTC by gorrdy

demo https://www.youtube.com/watch?v=m6Be1W4tS_0, now it is a bit different but the idea remains.

2021-12-23 10:30 UTC, gorrdy commented
also fixes #7

2021-12-23 12:18 UTC, the-papi requested changes

2021-12-23 12:18 UTC, the-papi commented on MOONCLOCK/font.py
> +CHAR_CROSS = '\ue016'
That doesn't seem to be the correct hexadecimal counting :smile:

7, 8, 9, a, b, c, d, e, f, 11, 12, ....

2021-12-23 12:18 UTC, the-papi commented on MOONCLOCK/code.py
> +            display_group.render_string('{0}{1}{2}'.format(font.CHAR_WIFI, ' ', wifi_conf['ssid'][:8]), center=False)
`'{} {}'.format(font.CHAR_WIFI, wifi_conf['ssid'][:8])` is better

2021-12-23 12:18 UTC, the-papi commented on MOONCLOCK/code.py
> +            display_group.render_string('{0}{1}'.format(font.CHAR_CHECK, ' '), center=True)
`'{} '.format(font.CHAR_CHECK)`

2021-12-25 14:03 UTC, the-papi commented
Maybe we should also keep backwards compatibility with the old `secrets.py` file?

Something like...
```python
if isinstance(secrets, dict):
    secrets = [secrets]
```

2021-12-25 17:01 UTC, the-papi approved these changes

2021-12-25 17:01 UTC, merged